#!/usr/bin/env python3
"""Generate po/*.po files for RT-Extension-AdminDashboard."""

import os

# All strings used in the extension via loc()
# Key = English msgid, value = dict of lang -> msgstr
TRANSLATIONS = {
    "Active": {
        "ar": "نشط",
        "bg": "Активен",
        "ca": "Actiu",
        "cs": "Aktivní",
        "da": "Aktiv",
        "de": "Aktiv",
        "el": "Ενεργός",
        "en_GB": "Active",
        "es": "Activo",
        "et": "Aktiivne",
        "eu": "Aktibo",
        "fa": "فعال",
        "fi": "Aktiivinen",
        "fr": "Actif",
        "hr": "Aktivan",
        "hu": "Aktív",
        "id": "Aktif",
        "is": "Virkt",
        "it": "Attivo",
        "ja": "アクティブ",
        "lt": "Aktyvus",
        "lv": "Aktīvs",
        "nb": "Aktiv",
        "nl": "Actief",
        "nn": "Aktiv",
        "pl": "Aktywny",
        "pt": "Ativo",
        "pt_BR": "Ativo",
        "pt_PT": "Ativo",
        "ru": "Активный",
        "sk": "Aktívny",
        "sl": "Aktiven",
        "sr": "Активан",
        "sv": "Aktiv",
        "tr": "Aktif",
        "zh_CN": "活跃",
        "zh_TW": "活躍",
    },
    "Configuration": {
        "ar": "الإعدادات",
        "bg": "Конфигурация",
        "ca": "Configuració",
        "cs": "Konfigurace",
        "da": "Konfiguration",
        "de": "Konfiguration",
        "el": "Ρυθμίσεις",
        "en_GB": "Configuration",
        "es": "Configuración",
        "et": "Seaded",
        "eu": "Konfigurazioa",
        "fa": "پیکربندی",
        "fi": "Asetukset",
        "fr": "Configuration",
        "hr": "Konfiguracija",
        "hu": "Konfiguráció",
        "id": "Konfigurasi",
        "is": "Stillingar",
        "it": "Configurazione",
        "ja": "設定",
        "lt": "Konfigūracija",
        "lv": "Konfigurācija",
        "nb": "Konfigurasjon",
        "nl": "Configuratie",
        "nn": "Konfigurasjon",
        "pl": "Konfiguracja",
        "pt": "Configuração",
        "pt_BR": "Configuração",
        "pt_PT": "Configuração",
        "ru": "Конфигурация",
        "sk": "Konfigurácia",
        "sl": "Konfiguracija",
        "sr": "Конфигурација",
        "sv": "Konfiguration",
        "tr": "Yapılandırma",
        "zh_CN": "配置",
        "zh_TW": "設定",
    },
    "Custom Fields": {
        "ar": "الحقول المخصصة",
        "bg": "Потребителски полета",
        "ca": "Camps personalitzats",
        "cs": "Vlastní pole",
        "da": "Brugerdefinerede felter",
        "de": "Benutzerdefinierte Felder",
        "el": "Προσαρμοσμένα πεδία",
        "en_GB": "Custom Fields",
        "es": "Campos personalizados",
        "et": "Kohandatud väljad",
        "eu": "Eremu pertsonalizatuak",
        "fa": "فیلدهای سفارشی",
        "fi": "Mukautetut kentät",
        "fr": "Champs personnalisés",
        "hr": "Prilagođena polja",
        "hu": "Egyéni mezők",
        "id": "Bidang kustom",
        "is": "Sérsniðin svæði",
        "it": "Campi personalizzati",
        "ja": "カスタムフィールド",
        "lt": "Pasirinktiniai laukai",
        "lv": "Pielāgotie lauki",
        "nb": "Egendefinerte felt",
        "nl": "Aangepaste velden",
        "nn": "Eigendefinerte felt",
        "pl": "Pola niestandardowe",
        "pt": "Campos personalizados",
        "pt_BR": "Campos personalizados",
        "pt_PT": "Campos personalizados",
        "ru": "Пользовательские поля",
        "sk": "Vlastné polia",
        "sl": "Polja po meri",
        "sr": "Прилагођена поља",
        "sv": "Anpassade fält",
        "tr": "Özel alanlar",
        "zh_CN": "自定义字段",
        "zh_TW": "自訂欄位",
    },
    "Deleted": {
        "ar": "محذوف",
        "bg": "Изтрит",
        "ca": "Eliminat",
        "cs": "Smazáno",
        "da": "Slettet",
        "de": "Gelöscht",
        "el": "Διαγράφηκε",
        "en_GB": "Deleted",
        "es": "Eliminado",
        "et": "Kustutatud",
        "eu": "Ezabatua",
        "fa": "حذف شده",
        "fi": "Poistettu",
        "fr": "Supprimé",
        "hr": "Obrisano",
        "hu": "Törölve",
        "id": "Dihapus",
        "is": "Eytt",
        "it": "Eliminato",
        "ja": "削除済み",
        "lt": "Ištrintas",
        "lv": "Dzēsts",
        "nb": "Slettet",
        "nl": "Verwijderd",
        "nn": "Sletta",
        "pl": "Usunięty",
        "pt": "Excluído",
        "pt_BR": "Excluído",
        "pt_PT": "Eliminado",
        "ru": "Удалён",
        "sk": "Zmazané",
        "sl": "Izbrisano",
        "sr": "Обрисано",
        "sv": "Raderad",
        "tr": "Silindi",
        "zh_CN": "已删除",
        "zh_TW": "已刪除",
    },
    "Disabled": {
        "ar": "معطّل",
        "bg": "Деактивиран",
        "ca": "Desactivat",
        "cs": "Vypnuto",
        "da": "Deaktiveret",
        "de": "Deaktiviert",
        "el": "Ανενεργό",
        "en_GB": "Disabled",
        "es": "Desactivado",
        "et": "Keelatud",
        "eu": "Desgaitua",
        "fa": "غیرفعال",
        "fi": "Poistettu käytöstä",
        "fr": "Désactivé",
        "hr": "Onemogućeno",
        "hu": "Letiltva",
        "id": "Dinonaktifkan",
        "is": "Óvirkt",
        "it": "Disabilitato",
        "ja": "無効",
        "lt": "Išjungtas",
        "lv": "Atspējots",
        "nb": "Deaktivert",
        "nl": "Uitgeschakeld",
        "nn": "Deaktivert",
        "pl": "Wyłączony",
        "pt": "Desativado",
        "pt_BR": "Desativado",
        "pt_PT": "Desativado",
        "ru": "Отключён",
        "sk": "Vypnuté",
        "sl": "Onemogočeno",
        "sr": "Онемогућено",
        "sv": "Inaktiverad",
        "tr": "Devre dışı",
        "zh_CN": "已禁用",
        "zh_TW": "已停用",
    },
    "Groups": {
        "ar": "المجموعات",
        "bg": "Групи",
        "ca": "Grups",
        "cs": "Skupiny",
        "da": "Grupper",
        "de": "Gruppen",
        "el": "Ομάδες",
        "en_GB": "Groups",
        "es": "Grupos",
        "et": "Grupid",
        "eu": "Taldeak",
        "fa": "گروه‌ها",
        "fi": "Ryhmät",
        "fr": "Groupes",
        "hr": "Grupe",
        "hu": "Csoportok",
        "id": "Grup",
        "is": "Hópar",
        "it": "Gruppi",
        "ja": "グループ",
        "lt": "Grupės",
        "lv": "Grupas",
        "nb": "Grupper",
        "nl": "Groepen",
        "nn": "Grupper",
        "pl": "Grupy",
        "pt": "Grupos",
        "pt_BR": "Grupos",
        "pt_PT": "Grupos",
        "ru": "Группы",
        "sk": "Skupiny",
        "sl": "Skupine",
        "sr": "Групе",
        "sv": "Grupper",
        "tr": "Gruplar",
        "zh_CN": "组",
        "zh_TW": "群組",
    },
    "New": {
        "ar": "جديد",
        "bg": "Нов",
        "ca": "Nou",
        "cs": "Nový",
        "da": "Ny",
        "de": "Neu",
        "el": "Νέο",
        "en_GB": "New",
        "es": "Nuevo",
        "et": "Uus",
        "eu": "Berria",
        "fa": "جدید",
        "fi": "Uusi",
        "fr": "Nouveau",
        "hr": "Novo",
        "hu": "Új",
        "id": "Baru",
        "is": "Nýtt",
        "it": "Nuovo",
        "ja": "新規",
        "lt": "Naujas",
        "lv": "Jauns",
        "nb": "Ny",
        "nl": "Nieuw",
        "nn": "Ny",
        "pl": "Nowy",
        "pt": "Novo",
        "pt_BR": "Novo",
        "pt_PT": "Novo",
        "ru": "Новый",
        "sk": "Nový",
        "sl": "Novo",
        "sr": "Ново",
        "sv": "Ny",
        "tr": "Yeni",
        "zh_CN": "新建",
        "zh_TW": "新建",
    },
    "Privileged": {
        "ar": "متميز",
        "bg": "Привилегирован",
        "ca": "Privilegiat",
        "cs": "Privilegovaný",
        "da": "Privilegeret",
        "de": "Privilegiert",
        "el": "Προνομιούχος",
        "en_GB": "Privileged",
        "es": "Privilegiado",
        "et": "Privilegeeritud",
        "eu": "Pribilegiatua",
        "fa": "دارای امتیاز",
        "fi": "Etuoikeutettu",
        "fr": "Privilégié",
        "hr": "Privilegiran",
        "hu": "Kiemelt",
        "id": "Istimewa",
        "is": "Forréttindanotandi",
        "it": "Privilegiato",
        "ja": "特権ユーザー",
        "lt": "Privilegijuotas",
        "lv": "Privileģēts",
        "nb": "Privilegert",
        "nl": "Geprivilegieerd",
        "nn": "Privilegert",
        "pl": "Uprzywilejowany",
        "pt": "Privilegiado",
        "pt_BR": "Privilegiado",
        "pt_PT": "Privilegiado",
        "ru": "Привилегированный",
        "sk": "Privilegovaný",
        "sl": "Privilegiran",
        "sr": "Привилегован",
        "sv": "Privilegierad",
        "tr": "Ayrıcalıklı",
        "zh_CN": "特权用户",
        "zh_TW": "特權用戶",
    },
    "Queues": {
        "ar": "الطوابير",
        "bg": "Опашки",
        "ca": "Cues",
        "cs": "Fronty",
        "da": "Køer",
        "de": "Bereiche",
        "el": "Ουρές",
        "en_GB": "Queues",
        "es": "Colas",
        "et": "Järjekorrad",
        "eu": "Ilarak",
        "fa": "صف‌ها",
        "fi": "Jonot",
        "fr": "Files d'attente",
        "hr": "Redovi",
        "hu": "Várólisták",
        "id": "Antrian",
        "is": "Biðraðir",
        "it": "Code",
        "ja": "キュー",
        "lt": "Eilės",
        "lv": "Rindas",
        "nb": "Køer",
        "nl": "Wachtrijen",
        "nn": "Køar",
        "pl": "Kolejki",
        "pt": "Filas",
        "pt_BR": "Filas",
        "pt_PT": "Filas",
        "ru": "Очереди",
        "sk": "Fronty",
        "sl": "Čakalne vrste",
        "sr": "Редови",
        "sv": "Köer",
        "tr": "Kuyruklar",
        "zh_CN": "队列",
        "zh_TW": "佇列",
    },
    "Resolved": {
        "ar": "محلول",
        "bg": "Решен",
        "ca": "Resolt",
        "cs": "Vyřešeno",
        "da": "Løst",
        "de": "Erledigt",
        "el": "Επιλύθηκε",
        "en_GB": "Resolved",
        "es": "Resuelto",
        "et": "Lahendatud",
        "eu": "Ebatzita",
        "fa": "حل شده",
        "fi": "Ratkaistu",
        "fr": "Résolu",
        "hr": "Riješeno",
        "hu": "Megoldva",
        "id": "Diselesaikan",
        "is": "Leyst",
        "it": "Risolto",
        "ja": "解決済み",
        "lt": "Išspręstas",
        "lv": "Atrisināts",
        "nb": "Løst",
        "nl": "Opgelost",
        "nn": "Løyst",
        "pl": "Rozwiązany",
        "pt": "Resolvido",
        "pt_BR": "Resolvido",
        "pt_PT": "Resolvido",
        "ru": "Решён",
        "sk": "Vyriešené",
        "sl": "Rešeno",
        "sr": "Решено",
        "sv": "Löst",
        "tr": "Çözüldü",
        "zh_CN": "已解决",
        "zh_TW": "已解決",
    },
    "Total": {
        "ar": "الإجمالي",
        "bg": "Общо",
        "ca": "Total",
        "cs": "Celkem",
        "da": "Total",
        "de": "Gesamt",
        "el": "Σύνολο",
        "en_GB": "Total",
        "es": "Total",
        "et": "Kokku",
        "eu": "Guztira",
        "fa": "مجموع",
        "fi": "Yhteensä",
        "fr": "Total",
        "hr": "Ukupno",
        "hu": "Összesen",
        "id": "Total",
        "is": "Alls",
        "it": "Totale",
        "ja": "合計",
        "lt": "Viso",
        "lv": "Kopā",
        "nb": "Totalt",
        "nl": "Totaal",
        "nn": "Totalt",
        "pl": "Łącznie",
        "pt": "Total",
        "pt_BR": "Total",
        "pt_PT": "Total",
        "ru": "Всего",
        "sk": "Celkom",
        "sl": "Skupaj",
        "sr": "Укупно",
        "sv": "Totalt",
        "tr": "Toplam",
        "zh_CN": "总计",
        "zh_TW": "總計",
    },
    "Tickets total": {
        "ar": "إجمالي التذاكر",
        "bg": "Общо заявки",
        "ca": "Total de tiquets",
        "cs": "Celkem požadavků",
        "da": "Sager i alt",
        "de": "Tickets gesamt",
        "el": "Σύνολο αιτημάτων",
        "en_GB": "Tickets total",
        "es": "Total de tickets",
        "et": "Pileteid kokku",
        "eu": "Txartelak guztira",
        "fa": "مجموع درخواست‌ها",
        "fi": "Tikettejä yhteensä",
        "fr": "Total des tickets",
        "hr": "Ukupno zahtjeva",
        "hu": "Jegyek összesen",
        "id": "Total tiket",
        "is": "Mál alls",
        "it": "Totale ticket",
        "ja": "チケット合計",
        "lt": "Iš viso užklausų",
        "lv": "Pieteikumu kopskaits",
        "nb": "Totalt antall saker",
        "nl": "Totaal tickets",
        "nn": "Totalt tal saker",
        "pl": "Łącznie zgłoszeń",
        "pt": "Total de tickets",
        "pt_BR": "Total de tickets",
        "pt_PT": "Total de tickets",
        "ru": "Заявок всего",
        "sk": "Celkom požiadaviek",
        "sl": "Skupaj zahtevkov",
        "sr": "Укупно захтева",
        "sv": "Totalt antal ärenden",
        "tr": "Toplam biletler",
        "zh_CN": "工单总数",
        "zh_TW": "工單總數",
    },
    "Unprivileged": {
        "ar": "غير متميز",
        "bg": "Непривилегирован",
        "ca": "No privilegiat",
        "cs": "Neprivilegovaný",
        "da": "Ikke-privilegeret",
        "de": "Unprivilegiert",
        "el": "Μη προνομιούχος",
        "en_GB": "Unprivileged",
        "es": "Sin privilegios",
        "et": "Privilegeerimata",
        "eu": "Ez-pribilegiatua",
        "fa": "بدون امتیاز",
        "fi": "Ei-etuoikeutettu",
        "fr": "Non privilégié",
        "hr": "Neprivilegiran",
        "hu": "Nem kiemelt",
        "id": "Tidak istimewa",
        "is": "Venjulegur notandi",
        "it": "Non privilegiato",
        "ja": "一般ユーザー",
        "lt": "Neprivilegijuotas",
        "lv": "Neprivileģēts",
        "nb": "Ikke-privilegert",
        "nl": "Niet geprivilegieerd",
        "nn": "Ikkje-privilegert",
        "pl": "Nieuprzywilejowany",
        "pt": "Sem privilégios",
        "pt_BR": "Sem privilégios",
        "pt_PT": "Sem privilégios",
        "ru": "Непривилегированный",
        "sk": "Neprivilegovaný",
        "sl": "Neprivilegiran",
        "sr": "Непривилегован",
        "sv": "Icke-privilegierad",
        "tr": "Ayrıcalıksız",
        "zh_CN": "普通用户",
        "zh_TW": "一般用戶",
    },
    "Active Classes": {
        "ar": "الفئات النشطة",
        "bg": "Активни класове",
        "ca": "Classes actives",
        "cs": "Aktivní třídy",
        "da": "Aktive klasser",
        "de": "Aktive Klassen",
        "el": "Ενεργές κατηγορίες",
        "en_GB": "Active Classes",
        "es": "Clases activas",
        "et": "Aktiivsed klassid",
        "eu": "Klase aktiboak",
        "fa": "کلاس‌های فعال",
        "fi": "Aktiiviset luokat",
        "fr": "Classes actives",
        "hr": "Aktivne klase",
        "hu": "Aktív osztályok",
        "id": "Kelas aktif",
        "is": "Virkar flokkar",
        "it": "Classi attive",
        "ja": "アクティブなクラス",
        "lt": "Aktyvios klasės",
        "lv": "Aktīvās klases",
        "nb": "Aktive klasser",
        "nl": "Actieve klassen",
        "nn": "Aktive klassar",
        "pl": "Aktywne klasy",
        "pt": "Classes ativas",
        "pt_BR": "Classes ativas",
        "pt_PT": "Classes ativas",
        "ru": "Активные классы",
        "sk": "Aktívne triedy",
        "sl": "Aktivni razredi",
        "sr": "Активне класе",
        "sv": "Aktiva klasser",
        "tr": "Aktif sınıflar",
        "zh_CN": "活跃类别",
        "zh_TW": "活躍類別",
    },
    "Allocated": {
        "ar": "مُخصَّص",
        "bg": "Разпределен",
        "ca": "Assignat",
        "cs": "Přiděleno",
        "da": "Tildelt",
        "de": "Zugeteilt",
        "el": "Εκχωρημένο",
        "en_GB": "Allocated",
        "es": "Asignado",
        "et": "Eraldatud",
        "eu": "Esleituta",
        "fa": "تخصیص‌یافته",
        "fi": "Kohdistettu",
        "fr": "Attribué",
        "hr": "Dodijeljeno",
        "hu": "Kiosztva",
        "id": "Dialokasikan",
        "is": "Úthlutað",
        "it": "Assegnato",
        "ja": "割り当て済み",
        "lt": "Paskirta",
        "lv": "Piešķirts",
        "nb": "Tildelt",
        "nl": "Toegewezen",
        "nn": "Tildelt",
        "pl": "Przydzielony",
        "pt": "Alocado",
        "pt_BR": "Alocado",
        "pt_PT": "Alocado",
        "ru": "Выделен",
        "sk": "Priradené",
        "sl": "Dodeljeno",
        "sr": "Додељено",
        "sv": "Tilldelad",
        "tr": "Tahsis edildi",
        "zh_CN": "已分配",
        "zh_TW": "已分配",
    },
    "Articles total": {
        "ar": "إجمالي المقالات",
        "bg": "Общо статии",
        "ca": "Total d'articles",
        "cs": "Celkem článků",
        "da": "Artikler i alt",
        "de": "Artikel gesamt",
        "el": "Σύνολο άρθρων",
        "en_GB": "Articles total",
        "es": "Total de artículos",
        "et": "Artikleid kokku",
        "eu": "Artikuluak guztira",
        "fa": "مجموع مقالات",
        "fi": "Artikkeleita yhteensä",
        "fr": "Total des articles",
        "hr": "Ukupno članaka",
        "hu": "Cikkek összesen",
        "id": "Total artikel",
        "is": "Greinar alls",
        "it": "Totale articoli",
        "ja": "記事合計",
        "lt": "Iš viso straipsnių",
        "lv": "Rakstu kopskaits",
        "nb": "Totalt artikler",
        "nl": "Totaal artikelen",
        "nn": "Totalt artiklar",
        "pl": "Łącznie artykułów",
        "pt": "Total de artigos",
        "pt_BR": "Total de artigos",
        "pt_PT": "Total de artigos",
        "ru": "Статей всего",
        "sk": "Celkom článkov",
        "sl": "Skupaj člankov",
        "sr": "Укупно чланака",
        "sv": "Totalt artiklar",
        "tr": "Toplam makaleler",
        "zh_CN": "文章总数",
        "zh_TW": "文章總數",
    },
    "Assets total": {
        "ar": "إجمالي الأصول",
        "bg": "Общо активи",
        "ca": "Total d'actius",
        "cs": "Celkem aktiv",
        "da": "Aktiver i alt",
        "de": "Assets gesamt",
        "el": "Σύνολο περιουσιακών στοιχείων",
        "en_GB": "Assets total",
        "es": "Total de activos",
        "et": "Varasid kokku",
        "eu": "Aktiboak guztira",
        "fa": "مجموع دارایی‌ها",
        "fi": "Resursseja yhteensä",
        "fr": "Total des ressources",
        "hr": "Ukupno imovine",
        "hu": "Eszközök összesen",
        "id": "Total aset",
        "is": "Eignir alls",
        "it": "Totale risorse",
        "ja": "Asset合計",
        "lt": "Iš viso turto",
        "lv": "Aktīvu kopskaits",
        "nb": "Totalt eiendeler",
        "nl": "Totaal assets",
        "nn": "Totalt eigedelar",
        "pl": "Łącznie zasobów",
        "pt": "Total de ativos",
        "pt_BR": "Total de ativos",
        "pt_PT": "Total de ativos",
        "ru": "Активов всего",
        "sk": "Celkom aktív",
        "sl": "Skupaj sredstev",
        "sr": "Укупно средстава",
        "sv": "Totalt tillgångar",
        "tr": "Toplam varlıklar",
        "zh_CN": "Asset总数",
        "zh_TW": "Asset總數",
    },
    "Catalogs total": {
        "ar": "إجمالي الفهارس",
        "bg": "Общо каталози",
        "ca": "Total de catàlegs",
        "cs": "Celkem katalogů",
        "da": "Kataloger i alt",
        "de": "Kataloge gesamt",
        "el": "Σύνολο καταλόγων",
        "en_GB": "Catalogs total",
        "es": "Total de catálogos",
        "et": "Katalooge kokku",
        "eu": "Kataloguak guztira",
        "fa": "مجموع کاتالوگ‌ها",
        "fi": "Luetteloita yhteensä",
        "fr": "Total des catalogues",
        "hr": "Ukupno kataloga",
        "hu": "Katalógusok összesen",
        "id": "Total katalog",
        "is": "Vörulista alls",
        "it": "Totale cataloghi",
        "ja": "カタログ合計",
        "lt": "Iš viso katalogų",
        "lv": "Katalogu kopskaits",
        "nb": "Totalt kataloger",
        "nl": "Totaal catalogi",
        "nn": "Totalt katalogar",
        "pl": "Łącznie katalogów",
        "pt": "Total de catálogos",
        "pt_BR": "Total de catálogos",
        "pt_PT": "Total de catálogos",
        "ru": "Каталогов всего",
        "sk": "Celkom katalógov",
        "sl": "Skupaj katalogov",
        "sr": "Укупно каталога",
        "sv": "Totalt kataloger",
        "tr": "Toplam kataloglar",
        "zh_CN": "目录总数",
        "zh_TW": "目錄總數",
    },
    "Classes total": {
        "ar": "إجمالي الفئات",
        "bg": "Общо класове",
        "ca": "Total de classes",
        "cs": "Celkem tříd",
        "da": "Klasser i alt",
        "de": "Klassen gesamt",
        "el": "Σύνολο κατηγοριών",
        "en_GB": "Classes total",
        "es": "Total de clases",
        "et": "Klasse kokku",
        "eu": "Klaseak guztira",
        "fa": "مجموع کلاس‌ها",
        "fi": "Luokkia yhteensä",
        "fr": "Total des classes",
        "hr": "Ukupno klasa",
        "hu": "Osztályok összesen",
        "id": "Total kelas",
        "is": "Flokkar alls",
        "it": "Totale classi",
        "ja": "クラス合計",
        "lt": "Iš viso klasių",
        "lv": "Klašu kopskaits",
        "nb": "Totalt klasser",
        "nl": "Totaal klassen",
        "nn": "Totalt klassar",
        "pl": "Łącznie klas",
        "pt": "Total de classes",
        "pt_BR": "Total de classes",
        "pt_PT": "Total de classes",
        "ru": "Классов всего",
        "sk": "Celkom tried",
        "sl": "Skupaj razredov",
        "sr": "Укупно класа",
        "sv": "Totalt klasser",
        "tr": "Toplam sınıflar",
        "zh_CN": "类别总数",
        "zh_TW": "類別總數",
    },
    "Database Size (MB)": {
        "ar": "حجم قاعدة البيانات (ميغابايت)",
        "bg": "Размер на базата данни (МБ)",
        "ca": "Mida de la base de dades (MB)",
        "cs": "Velikost databáze (MB)",
        "da": "Databasestørrelse (MB)",
        "de": "Datenbankgröße (MB)",
        "el": "Μέγεθος βάσης δεδομένων (MB)",
        "en_GB": "Database Size (MB)",
        "es": "Tamaño de base de datos (MB)",
        "et": "Andmebaasi suurus (MB)",
        "eu": "Datu-basearen tamaina (MB)",
        "fa": "اندازه پایگاه داده (مگابایت)",
        "fi": "Tietokannan koko (MB)",
        "fr": "Taille de la base de données (Mo)",
        "hr": "Veličina baze podataka (MB)",
        "hu": "Adatbázis mérete (MB)",
        "id": "Ukuran basis data (MB)",
        "is": "Stærð gagnagrunns (MB)",
        "it": "Dimensione del database (MB)",
        "ja": "データベースサイズ (MB)",
        "lt": "Duomenų bazės dydis (MB)",
        "lv": "Datu bāzes izmērs (MB)",
        "nb": "Databasestørrelse (MB)",
        "nl": "Databasegrootte (MB)",
        "nn": "Databasestorleik (MB)",
        "pl": "Rozmiar bazy danych (MB)",
        "pt": "Tamanho do banco de dados (MB)",
        "pt_BR": "Tamanho do banco de dados (MB)",
        "pt_PT": "Tamanho da base de dados (MB)",
        "ru": "Размер базы данных (МБ)",
        "sk": "Veľkosť databázy (MB)",
        "sl": "Velikost baze podatkov (MB)",
        "sr": "Величина базе података (MB)",
        "sv": "Databasstorlek (MB)",
        "tr": "Veritabanı boyutu (MB)",
        "zh_CN": "数据库大小 (MB)",
        "zh_TW": "資料庫大小 (MB)",
    },
    "In Use": {
        "ar": "قيد الاستخدام",
        "bg": "В употреба",
        "ca": "En ús",
        "cs": "Používá se",
        "da": "I brug",
        "de": "In Benutzung",
        "el": "Σε χρήση",
        "en_GB": "In Use",
        "es": "En uso",
        "et": "Kasutusel",
        "eu": "Erabiltzen",
        "fa": "در حال استفاده",
        "fi": "Käytössä",
        "fr": "En cours d'utilisation",
        "hr": "U upotrebi",
        "hu": "Használatban",
        "id": "Sedang digunakan",
        "is": "Í notkun",
        "it": "In uso",
        "ja": "使用中",
        "lt": "Naudojama",
        "lv": "Lietošanā",
        "nb": "I bruk",
        "nl": "In gebruik",
        "nn": "I bruk",
        "pl": "W użyciu",
        "pt": "Em uso",
        "pt_BR": "Em uso",
        "pt_PT": "Em uso",
        "ru": "В использовании",
        "sk": "Používa sa",
        "sl": "V uporabi",
        "sr": "У употреби",
        "sv": "I bruk",
        "tr": "Kullanımda",
        "zh_CN": "使用中",
        "zh_TW": "使用中",
    },
    "Other": {
        "ar": "أخرى",
        "bg": "Друго",
        "ca": "Altres",
        "cs": "Ostatní",
        "da": "Andet",
        "de": "Sonstige",
        "el": "Άλλο",
        "en_GB": "Other",
        "es": "Otros",
        "et": "Muu",
        "eu": "Beste",
        "fa": "سایر",
        "fi": "Muu",
        "fr": "Autre",
        "hr": "Ostalo",
        "hu": "Egyéb",
        "id": "Lainnya",
        "is": "Annað",
        "it": "Altro",
        "ja": "その他",
        "lt": "Kita",
        "lv": "Citi",
        "nb": "Annet",
        "nl": "Overig",
        "nn": "Anna",
        "pl": "Inne",
        "pt": "Outro",
        "pt_BR": "Outro",
        "pt_PT": "Outro",
        "ru": "Прочее",
        "sk": "Iné",
        "sl": "Drugo",
        "sr": "Остало",
        "sv": "Övrigt",
        "tr": "Diğer",
        "zh_CN": "其他",
        "zh_TW": "其他",
    },
    "Mail Errors": {
        "ar": "أخطاء البريد",
        "bg": "Грешки при изпращане на поща",
        "ca": "Errors de correu",
        "cs": "Chyby e-mailu",
        "da": "E-mailfejl",
        "de": "E-Mail-Fehler",
        "el": "Σφάλματα αλληλογραφίας",
        "en_GB": "Mail Errors",
        "es": "Errores de correo",
        "et": "Meilivead",
        "eu": "Posta-akatsak",
        "fa": "خطاهای ایمیل",
        "fi": "Sähköpostivirheet",
        "fr": "Erreurs de messagerie",
        "hr": "Greške pošte",
        "hu": "Levélküldési hibák",
        "id": "Kesalahan email",
        "is": "Tölvupóstvillur",
        "it": "Errori di posta",
        "ja": "メールエラー",
        "lt": "Pašto klaidos",
        "lv": "Pasta kļūdas",
        "nb": "E-postfeil",
        "nl": "Mailfouten",
        "nn": "E-postfeil",
        "pl": "Błędy poczty",
        "pt": "Erros de e-mail",
        "pt_BR": "Erros de e-mail",
        "pt_PT": "Erros de e-mail",
        "ru": "Ошибки почты",
        "sk": "Chyby pošty",
        "sl": "Napake pošte",
        "sr": "Грешке поште",
        "sv": "E-postfel",
        "tr": "E-posta hataları",
        "zh_CN": "邮件错误",
        "zh_TW": "郵件錯誤",
    },
    "Global Scrips": {
        "ar": "سكريبتات عالمية",
        "bg": "Глобални скриптове",
        "ca": "Scrips globals",
        "cs": "Globální skripty",
        "da": "Globale scrips",
        "de": "Globale Scrips",
        "el": "Καθολικά scrips",
        "en_GB": "Global Scrips",
        "es": "Scrips globales",
        "et": "Globaalsed skriptid",
        "eu": "Scrip globalak",
        "fa": "اسکریپت‌های سراسری",
        "fi": "Globaalit skipit",
        "fr": "Scrips globaux",
        "hr": "Globalni scrips",
        "hu": "Globális scrips-ek",
        "id": "Scrips global",
        "is": "Altækar scrips",
        "it": "Scrips globali",
        "ja": "グローバルScrip",
        "lt": "Globalūs skriptai",
        "lv": "Globālie skripti",
        "nb": "Globale scrips",
        "nl": "Globale scrips",
        "nn": "Globale scrips",
        "pl": "Globalne skrypty",
        "pt": "Scrips globais",
        "pt_BR": "Scrips globais",
        "pt_PT": "Scrips globais",
        "ru": "Глобальные скрипты",
        "sk": "Globálne skripty",
        "sl": "Globalni skripti",
        "sr": "Глобални скрипти",
        "sv": "Globala scrips",
        "tr": "Global scrips",
        "zh_CN": "全局Scrip",
        "zh_TW": "全域Scrip",
    },
    "Queue-specific": {
        "ar": "خاص بالطابور",
        "bg": "Специфичен за опашка",
        "ca": "Específic de cua",
        "cs": "Specifické pro frontu",
        "da": "Kø-specifik",
        "de": "Bereichsspezifisch",
        "el": "Ειδικό ουράς",
        "en_GB": "Queue-specific",
        "es": "Específico de cola",
        "et": "Järjekorrapõhine",
        "eu": "Ilara-espezifikoa",
        "fa": "مختص صف",
        "fi": "Jono-kohtainen",
        "fr": "Spécifique à la file",
        "hr": "Specifičan za red",
        "hu": "Várólistaspecifikus",
        "id": "Spesifik antrean",
        "is": "Sértækt fyrir biðröð",
        "it": "Specifico della coda",
        "ja": "キュー固有",
        "lt": "Eilės specifinis",
        "lv": "Rindai specifisks",
        "nb": "Køspesifikk",
        "nl": "Wachtrij-specifiek",
        "nn": "Køspesifikk",
        "pl": "Specyficzny dla kolejki",
        "pt": "Específico da fila",
        "pt_BR": "Específico da fila",
        "pt_PT": "Específico da fila",
        "ru": "Специфичный для очереди",
        "sk": "Špecifický pre frontu",
        "sl": "Specifično za čakalno vrsto",
        "sr": "Специфично за ред",
        "sv": "Kö-specifik",
        "tr": "Kuyruk-özel",
        "zh_CN": "队列专属",
        "zh_TW": "佇列專屬",
    },
    "Scrips total": {
        "ar": "إجمالي السكريبتات",
        "bg": "Общо скриптове",
        "ca": "Total de scrips",
        "cs": "Celkem skriptů",
        "da": "Scrips i alt",
        "de": "Scrips gesamt",
        "el": "Σύνολο scrips",
        "en_GB": "Scrips total",
        "es": "Total de scrips",
        "et": "Skripte kokku",
        "eu": "Scrips guztira",
        "fa": "مجموع اسکریپت‌ها",
        "fi": "Skipit yhteensä",
        "fr": "Total des scrips",
        "hr": "Ukupno scrips",
        "hu": "Összes scrips",
        "id": "Total scrips",
        "is": "Scrips alls",
        "it": "Totale scrips",
        "ja": "Scrip合計",
        "lt": "Iš viso skriptų",
        "lv": "Skriptu kopskaits",
        "nb": "Totalt scrips",
        "nl": "Totaal scrips",
        "nn": "Totalt scrips",
        "pl": "Łącznie skryptów",
        "pt": "Total de scrips",
        "pt_BR": "Total de scrips",
        "pt_PT": "Total de scrips",
        "ru": "Скриптов всего",
        "sk": "Celkom skriptov",
        "sl": "Skupaj skriptov",
        "sr": "Укупно скрипти",
        "sv": "Totalt scrips",
        "tr": "Toplam scrips",
        "zh_CN": "Scrip总数",
        "zh_TW": "Scrip總數",
    },
    "Users": {
        "ar": "المستخدمون",
        "bg": "Потребители",
        "ca": "Usuaris",
        "cs": "Uživatelé",
        "da": "Brugere",
        "de": "Benutzer",
        "el": "Χρήστες",
        "en_GB": "Users",
        "es": "Usuarios",
        "et": "Kasutajad",
        "eu": "Erabiltzaileak",
        "fa": "کاربران",
        "fi": "Käyttäjät",
        "fr": "Utilisateurs",
        "hr": "Korisnici",
        "hu": "Felhasználók",
        "id": "Pengguna",
        "is": "Notendur",
        "it": "Utenti",
        "ja": "ユーザー",
        "lt": "Vartotojai",
        "lv": "Lietotāji",
        "nb": "Brukere",
        "nl": "Gebruikers",
        "nn": "Brukarar",
        "pl": "Użytkownicy",
        "pt": "Usuários",
        "pt_BR": "Usuários",
        "pt_PT": "Utilizadores",
        "ru": "Пользователи",
        "sk": "Používatelia",
        "sl": "Uporabniki",
        "sr": "Корисници",
        "sv": "Användare",
        "tr": "Kullanıcılar",
        "zh_CN": "用户",
        "zh_TW": "用戶",
    },
}

LANGUAGES = sorted({lang for translations in TRANSLATIONS.values() for lang in translations})

PO_HEADER = """\
# RT-Extension-AdminDashboard - {lang} translation
# Copyright (C) 2026 Torsten Brumm
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Language: {lang}\\n"

"""

os.makedirs("po", exist_ok=True)

# Write .pot template
with open("po/rt-extension-admindashboard.pot", "w", encoding="utf-8") as f:
    f.write('# RT-Extension-AdminDashboard translation template\n')
    f.write('msgid ""\nmsgstr ""\n')
    f.write('"Content-Type: text/plain; charset=UTF-8\\n"\n')
    f.write('"Content-Transfer-Encoding: 8bit\\n"\n\n')
    for msgid in sorted(TRANSLATIONS.keys()):
        f.write(f'msgid "{msgid}"\nmsgstr ""\n\n')

# Write per-language .po files
for lang in LANGUAGES:
    path = f"po/{lang}.po"
    with open(path, "w", encoding="utf-8") as f:
        f.write(PO_HEADER.format(lang=lang))
        for msgid in sorted(TRANSLATIONS.keys()):
            msgstr = TRANSLATIONS[msgid].get(lang, "")
            # Skip if translation equals msgid (no point restating it)
            if msgstr and msgstr != msgid:
                f.write(f'msgid "{msgid}"\nmsgstr "{msgstr}"\n\n')
    print(f"  wrote {path}")

print(f"\nDone. {len(LANGUAGES)} language files + 1 .pot template.")
