#!/usr/bin/env python3
"""Generate po/*.po files for RT-Extension-AdminDashboard."""

import os

# All strings used in the extension via loc()
# Key = English msgid, value = dict of lang -> msgstr
TRANSLATIONS = {
    "Active": {
        "ar": "نشط",
        "bg": "Активен",
        "ca": "Actiu",
        "cs": "Aktivní",
        "da": "Aktiv",
        "de": "Aktiv",
        "el": "Ενεργός",
        "en_GB": "Active",
        "es": "Activo",
        "et": "Aktiivne",
        "eu": "Aktibo",
        "fa": "فعال",
        "fi": "Aktiivinen",
        "fr": "Actif",
        "hr": "Aktivan",
        "hu": "Aktív",
        "id": "Aktif",
        "is": "Virkt",
        "it": "Attivo",
        "ja": "アクティブ",
        "lt": "Aktyvus",
        "lv": "Aktīvs",
        "nb": "Aktiv",
        "nl": "Actief",
        "nn": "Aktiv",
        "pl": "Aktywny",
        "pt": "Ativo",
        "pt_BR": "Ativo",
        "pt_PT": "Ativo",
        "ru": "Активный",
        "sk": "Aktívny",
        "sl": "Aktiven",
        "sr": "Активан",
        "sv": "Aktiv",
        "tr": "Aktif",
        "zh_CN": "活跃",
        "zh_TW": "活躍",
    },
    "Configuration": {
        "ar": "الإعدادات",
        "bg": "Конфигурация",
        "ca": "Configuració",
        "cs": "Konfigurace",
        "da": "Konfiguration",
        "de": "Konfiguration",
        "el": "Ρυθμίσεις",
        "en_GB": "Configuration",
        "es": "Configuración",
        "et": "Seaded",
        "eu": "Konfigurazioa",
        "fa": "پیکربندی",
        "fi": "Asetukset",
        "fr": "Configuration",
        "hr": "Konfiguracija",
        "hu": "Konfiguráció",
        "id": "Konfigurasi",
        "is": "Stillingar",
        "it": "Configurazione",
        "ja": "設定",
        "lt": "Konfigūracija",
        "lv": "Konfigurācija",
        "nb": "Konfigurasjon",
        "nl": "Configuratie",
        "nn": "Konfigurasjon",
        "pl": "Konfiguracja",
        "pt": "Configuração",
        "pt_BR": "Configuração",
        "pt_PT": "Configuração",
        "ru": "Конфигурация",
        "sk": "Konfigurácia",
        "sl": "Konfiguracija",
        "sr": "Конфигурација",
        "sv": "Konfiguration",
        "tr": "Yapılandırma",
        "zh_CN": "配置",
        "zh_TW": "設定",
    },
    "Custom Fields": {
        "ar": "الحقول المخصصة",
        "bg": "Потребителски полета",
        "ca": "Camps personalitzats",
        "cs": "Vlastní pole",
        "da": "Brugerdefinerede felter",
        "de": "Benutzerdefinierte Felder",
        "el": "Προσαρμοσμένα πεδία",
        "en_GB": "Custom Fields",
        "es": "Campos personalizados",
        "et": "Kohandatud väljad",
        "eu": "Eremu pertsonalizatuak",
        "fa": "فیلدهای سفارشی",
        "fi": "Mukautetut kentät",
        "fr": "Champs personnalisés",
        "hr": "Prilagođena polja",
        "hu": "Egyéni mezők",
        "id": "Bidang kustom",
        "is": "Sérsniðin svæði",
        "it": "Campi personalizzati",
        "ja": "カスタムフィールド",
        "lt": "Pasirinktiniai laukai",
        "lv": "Pielāgotie lauki",
        "nb": "Egendefinerte felt",
        "nl": "Aangepaste velden",
        "nn": "Eigendefinerte felt",
        "pl": "Pola niestandardowe",
        "pt": "Campos personalizados",
        "pt_BR": "Campos personalizados",
        "pt_PT": "Campos personalizados",
        "ru": "Пользовательские поля",
        "sk": "Vlastné polia",
        "sl": "Polja po meri",
        "sr": "Прилагођена поља",
        "sv": "Anpassade fält",
        "tr": "Özel alanlar",
        "zh_CN": "自定义字段",
        "zh_TW": "自訂欄位",
    },
    "Deleted": {
        "ar": "محذوف",
        "bg": "Изтрит",
        "ca": "Eliminat",
        "cs": "Smazáno",
        "da": "Slettet",
        "de": "Gelöscht",
        "el": "Διαγράφηκε",
        "en_GB": "Deleted",
        "es": "Eliminado",
        "et": "Kustutatud",
        "eu": "Ezabatua",
        "fa": "حذف شده",
        "fi": "Poistettu",
        "fr": "Supprimé",
        "hr": "Obrisano",
        "hu": "Törölve",
        "id": "Dihapus",
        "is": "Eytt",
        "it": "Eliminato",
        "ja": "削除済み",
        "lt": "Ištrintas",
        "lv": "Dzēsts",
        "nb": "Slettet",
        "nl": "Verwijderd",
        "nn": "Sletta",
        "pl": "Usunięty",
        "pt": "Excluído",
        "pt_BR": "Excluído",
        "pt_PT": "Eliminado",
        "ru": "Удалён",
        "sk": "Zmazané",
        "sl": "Izbrisano",
        "sr": "Обрисано",
        "sv": "Raderad",
        "tr": "Silindi",
        "zh_CN": "已删除",
        "zh_TW": "已刪除",
    },
    "Disabled": {
        "ar": "معطّل",
        "bg": "Деактивиран",
        "ca": "Desactivat",
        "cs": "Vypnuto",
        "da": "Deaktiveret",
        "de": "Deaktiviert",
        "el": "Ανενεργό",
        "en_GB": "Disabled",
        "es": "Desactivado",
        "et": "Keelatud",
        "eu": "Desgaitua",
        "fa": "غیرفعال",
        "fi": "Poistettu käytöstä",
        "fr": "Désactivé",
        "hr": "Onemogućeno",
        "hu": "Letiltva",
        "id": "Dinonaktifkan",
        "is": "Óvirkt",
        "it": "Disabilitato",
        "ja": "無効",
        "lt": "Išjungtas",
        "lv": "Atspējots",
        "nb": "Deaktivert",
        "nl": "Uitgeschakeld",
        "nn": "Deaktivert",
        "pl": "Wyłączony",
        "pt": "Desativado",
        "pt_BR": "Desativado",
        "pt_PT": "Desativado",
        "ru": "Отключён",
        "sk": "Vypnuté",
        "sl": "Onemogočeno",
        "sr": "Онемогућено",
        "sv": "Inaktiverad",
        "tr": "Devre dışı",
        "zh_CN": "已禁用",
        "zh_TW": "已停用",
    },
    "Groups": {
        "ar": "المجموعات",
        "bg": "Групи",
        "ca": "Grups",
        "cs": "Skupiny",
        "da": "Grupper",
        "de": "Gruppen",
        "el": "Ομάδες",
        "en_GB": "Groups",
        "es": "Grupos",
        "et": "Grupid",
        "eu": "Taldeak",
        "fa": "گروه‌ها",
        "fi": "Ryhmät",
        "fr": "Groupes",
        "hr": "Grupe",
        "hu": "Csoportok",
        "id": "Grup",
        "is": "Hópar",
        "it": "Gruppi",
        "ja": "グループ",
        "lt": "Grupės",
        "lv": "Grupas",
        "nb": "Grupper",
        "nl": "Groepen",
        "nn": "Grupper",
        "pl": "Grupy",
        "pt": "Grupos",
        "pt_BR": "Grupos",
        "pt_PT": "Grupos",
        "ru": "Группы",
        "sk": "Skupiny",
        "sl": "Skupine",
        "sr": "Групе",
        "sv": "Grupper",
        "tr": "Gruplar",
        "zh_CN": "组",
        "zh_TW": "群組",
    },
    "New": {
        "ar": "جديد",
        "bg": "Нов",
        "ca": "Nou",
        "cs": "Nový",
        "da": "Ny",
        "de": "Neu",
        "el": "Νέο",
        "en_GB": "New",
        "es": "Nuevo",
        "et": "Uus",
        "eu": "Berria",
        "fa": "جدید",
        "fi": "Uusi",
        "fr": "Nouveau",
        "hr": "Novo",
        "hu": "Új",
        "id": "Baru",
        "is": "Nýtt",
        "it": "Nuovo",
        "ja": "新規",
        "lt": "Naujas",
        "lv": "Jauns",
        "nb": "Ny",
        "nl": "Nieuw",
        "nn": "Ny",
        "pl": "Nowy",
        "pt": "Novo",
        "pt_BR": "Novo",
        "pt_PT": "Novo",
        "ru": "Новый",
        "sk": "Nový",
        "sl": "Novo",
        "sr": "Ново",
        "sv": "Ny",
        "tr": "Yeni",
        "zh_CN": "新建",
        "zh_TW": "新建",
    },
    "Privileged": {
        "ar": "متميز",
        "bg": "Привилегирован",
        "ca": "Privilegiat",
        "cs": "Privilegovaný",
        "da": "Privilegeret",
        "de": "Privilegiert",
        "el": "Προνομιούχος",
        "en_GB": "Privileged",
        "es": "Privilegiado",
        "et": "Privilegeeritud",
        "eu": "Pribilegiatua",
        "fa": "دارای امتیاز",
        "fi": "Etuoikeutettu",
        "fr": "Privilégié",
        "hr": "Privilegiran",
        "hu": "Kiemelt",
        "id": "Istimewa",
        "is": "Forréttindanotandi",
        "it": "Privilegiato",
        "ja": "特権ユーザー",
        "lt": "Privilegijuotas",
        "lv": "Privileģēts",
        "nb": "Privilegert",
        "nl": "Geprivilegieerd",
        "nn": "Privilegert",
        "pl": "Uprzywilejowany",
        "pt": "Privilegiado",
        "pt_BR": "Privilegiado",
        "pt_PT": "Privilegiado",
        "ru": "Привилегированный",
        "sk": "Privilegovaný",
        "sl": "Privilegiran",
        "sr": "Привилегован",
        "sv": "Privilegierad",
        "tr": "Ayrıcalıklı",
        "zh_CN": "特权用户",
        "zh_TW": "特權用戶",
    },
    "Queues": {
        "ar": "الطوابير",
        "bg": "Опашки",
        "ca": "Cues",
        "cs": "Fronty",
        "da": "Køer",
        "de": "Bereiche",
        "el": "Ουρές",
        "en_GB": "Queues",
        "es": "Colas",
        "et": "Järjekorrad",
        "eu": "Ilarak",
        "fa": "صف‌ها",
        "fi": "Jonot",
        "fr": "Files d'attente",
        "hr": "Redovi",
        "hu": "Várólisták",
        "id": "Antrian",
        "is": "Biðraðir",
        "it": "Code",
        "ja": "キュー",
        "lt": "Eilės",
        "lv": "Rindas",
        "nb": "Køer",
        "nl": "Wachtrijen",
        "nn": "Køar",
        "pl": "Kolejki",
        "pt": "Filas",
        "pt_BR": "Filas",
        "pt_PT": "Filas",
        "ru": "Очереди",
        "sk": "Fronty",
        "sl": "Čakalne vrste",
        "sr": "Редови",
        "sv": "Köer",
        "tr": "Kuyruklar",
        "zh_CN": "队列",
        "zh_TW": "佇列",
    },
    "Resolved": {
        "ar": "محلول",
        "bg": "Решен",
        "ca": "Resolt",
        "cs": "Vyřešeno",
        "da": "Løst",
        "de": "Erledigt",
        "el": "Επιλύθηκε",
        "en_GB": "Resolved",
        "es": "Resuelto",
        "et": "Lahendatud",
        "eu": "Ebatzita",
        "fa": "حل شده",
        "fi": "Ratkaistu",
        "fr": "Résolu",
        "hr": "Riješeno",
        "hu": "Megoldva",
        "id": "Diselesaikan",
        "is": "Leyst",
        "it": "Risolto",
        "ja": "解決済み",
        "lt": "Išspręstas",
        "lv": "Atrisināts",
        "nb": "Løst",
        "nl": "Opgelost",
        "nn": "Løyst",
        "pl": "Rozwiązany",
        "pt": "Resolvido",
        "pt_BR": "Resolvido",
        "pt_PT": "Resolvido",
        "ru": "Решён",
        "sk": "Vyriešené",
        "sl": "Rešeno",
        "sr": "Решено",
        "sv": "Löst",
        "tr": "Çözüldü",
        "zh_CN": "已解决",
        "zh_TW": "已解決",
    },
    "Total": {
        "ar": "الإجمالي",
        "bg": "Общо",
        "ca": "Total",
        "cs": "Celkem",
        "da": "Total",
        "de": "Gesamt",
        "el": "Σύνολο",
        "en_GB": "Total",
        "es": "Total",
        "et": "Kokku",
        "eu": "Guztira",
        "fa": "مجموع",
        "fi": "Yhteensä",
        "fr": "Total",
        "hr": "Ukupno",
        "hu": "Összesen",
        "id": "Total",
        "is": "Alls",
        "it": "Totale",
        "ja": "合計",
        "lt": "Viso",
        "lv": "Kopā",
        "nb": "Totalt",
        "nl": "Totaal",
        "nn": "Totalt",
        "pl": "Łącznie",
        "pt": "Total",
        "pt_BR": "Total",
        "pt_PT": "Total",
        "ru": "Всего",
        "sk": "Celkom",
        "sl": "Skupaj",
        "sr": "Укупно",
        "sv": "Totalt",
        "tr": "Toplam",
        "zh_CN": "总计",
        "zh_TW": "總計",
    },
    "Tickets total": {
        "ar": "إجمالي التذاكر",
        "bg": "Общо заявки",
        "ca": "Total de tiquets",
        "cs": "Celkem požadavků",
        "da": "Sager i alt",
        "de": "Tickets gesamt",
        "el": "Σύνολο αιτημάτων",
        "en_GB": "Tickets total",
        "es": "Total de tickets",
        "et": "Pileteid kokku",
        "eu": "Txartelak guztira",
        "fa": "مجموع درخواست‌ها",
        "fi": "Tikettejä yhteensä",
        "fr": "Total des tickets",
        "hr": "Ukupno zahtjeva",
        "hu": "Jegyek összesen",
        "id": "Total tiket",
        "is": "Mál alls",
        "it": "Totale ticket",
        "ja": "チケット合計",
        "lt": "Iš viso užklausų",
        "lv": "Pieteikumu kopskaits",
        "nb": "Totalt antall saker",
        "nl": "Totaal tickets",
        "nn": "Totalt tal saker",
        "pl": "Łącznie zgłoszeń",
        "pt": "Total de tickets",
        "pt_BR": "Total de tickets",
        "pt_PT": "Total de tickets",
        "ru": "Заявок всего",
        "sk": "Celkom požiadaviek",
        "sl": "Skupaj zahtevkov",
        "sr": "Укупно захтева",
        "sv": "Totalt antal ärenden",
        "tr": "Toplam biletler",
        "zh_CN": "工单总数",
        "zh_TW": "工單總數",
    },
    "Unprivileged": {
        "ar": "غير متميز",
        "bg": "Непривилегирован",
        "ca": "No privilegiat",
        "cs": "Neprivilegovaný",
        "da": "Ikke-privilegeret",
        "de": "Unprivilegiert",
        "el": "Μη προνομιούχος",
        "en_GB": "Unprivileged",
        "es": "Sin privilegios",
        "et": "Privilegeerimata",
        "eu": "Ez-pribilegiatua",
        "fa": "بدون امتیاز",
        "fi": "Ei-etuoikeutettu",
        "fr": "Non privilégié",
        "hr": "Neprivilegiran",
        "hu": "Nem kiemelt",
        "id": "Tidak istimewa",
        "is": "Venjulegur notandi",
        "it": "Non privilegiato",
        "ja": "一般ユーザー",
        "lt": "Neprivilegijuotas",
        "lv": "Neprivileģēts",
        "nb": "Ikke-privilegert",
        "nl": "Niet geprivilegieerd",
        "nn": "Ikkje-privilegert",
        "pl": "Nieuprzywilejowany",
        "pt": "Sem privilégios",
        "pt_BR": "Sem privilégios",
        "pt_PT": "Sem privilégios",
        "ru": "Непривилегированный",
        "sk": "Neprivilegovaný",
        "sl": "Neprivilegiran",
        "sr": "Непривилегован",
        "sv": "Icke-privilegierad",
        "tr": "Ayrıcalıksız",
        "zh_CN": "普通用户",
        "zh_TW": "一般用戶",
    },
    "Users": {
        "ar": "المستخدمون",
        "bg": "Потребители",
        "ca": "Usuaris",
        "cs": "Uživatelé",
        "da": "Brugere",
        "de": "Benutzer",
        "el": "Χρήστες",
        "en_GB": "Users",
        "es": "Usuarios",
        "et": "Kasutajad",
        "eu": "Erabiltzaileak",
        "fa": "کاربران",
        "fi": "Käyttäjät",
        "fr": "Utilisateurs",
        "hr": "Korisnici",
        "hu": "Felhasználók",
        "id": "Pengguna",
        "is": "Notendur",
        "it": "Utenti",
        "ja": "ユーザー",
        "lt": "Vartotojai",
        "lv": "Lietotāji",
        "nb": "Brukere",
        "nl": "Gebruikers",
        "nn": "Brukarar",
        "pl": "Użytkownicy",
        "pt": "Usuários",
        "pt_BR": "Usuários",
        "pt_PT": "Utilizadores",
        "ru": "Пользователи",
        "sk": "Používatelia",
        "sl": "Uporabniki",
        "sr": "Корисници",
        "sv": "Användare",
        "tr": "Kullanıcılar",
        "zh_CN": "用户",
        "zh_TW": "用戶",
    },
}

LANGUAGES = sorted({lang for translations in TRANSLATIONS.values() for lang in translations})

PO_HEADER = """\
# RT-Extension-AdminDashboard - {lang} translation
# Copyright (C) 2026 Torsten Brumm
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Language: {lang}\\n"

"""

os.makedirs("po", exist_ok=True)

# Write .pot template
with open("po/rt-extension-admindashboard.pot", "w", encoding="utf-8") as f:
    f.write('# RT-Extension-AdminDashboard translation template\n')
    f.write('msgid ""\nmsgstr ""\n')
    f.write('"Content-Type: text/plain; charset=UTF-8\\n"\n')
    f.write('"Content-Transfer-Encoding: 8bit\\n"\n\n')
    for msgid in sorted(TRANSLATIONS.keys()):
        f.write(f'msgid "{msgid}"\nmsgstr ""\n\n')

# Write per-language .po files
for lang in LANGUAGES:
    path = f"po/{lang}.po"
    with open(path, "w", encoding="utf-8") as f:
        f.write(PO_HEADER.format(lang=lang))
        for msgid in sorted(TRANSLATIONS.keys()):
            msgstr = TRANSLATIONS[msgid].get(lang, "")
            # Skip if translation equals msgid (no point restating it)
            if msgstr and msgstr != msgid:
                f.write(f'msgid "{msgid}"\nmsgstr "{msgstr}"\n\n')
    print(f"  wrote {path}")

print(f"\nDone. {len(LANGUAGES)} language files + 1 .pot template.")
